services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    ports:
      - '${POSTGRES_PORT:-5432}:5432'
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-proserv}
      POSTGRES_USER: ${POSTGRES_USER:-proserv}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-proserv}
    volumes:
      - proserv-postgres:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - '${REDIS_PORT:-6379}:6379'

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9090"
    restart: unless-stopped
    ports:
      - '${MINIO_PORT:-9000}:9000'
      - '${MINIO_CONSOLE_PORT:-9090}:9090'
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minio}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minio-secret}
    volumes:
      - proserv-minio:/data

  mailpit:
    image: axllent/mailpit:v1.20
    restart: unless-stopped
    ports:
      - '${MAILPIT_SMTP_PORT:-1025}:1025'
      - '${MAILPIT_HTTP_PORT:-8025}:8025'

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.98.0
    restart: unless-stopped
    command: ['--config=/etc/otel-collector-config.yml']
    volumes:
      - ./ops/otel/collector.yml:/etc/otel-collector-config.yml:ro
    ports:
      - '${OTEL_EXPORTER_OTLP_PORT:-4317}:4317'

  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    env_file:
      - apps/api/.env.docker
    environment:
      DATABASE_URL: ${DATABASE_URL:-postgresql://proserv:proserv@postgres:5432/proserv}
      SHADOW_DATABASE_URL: ${SHADOW_DATABASE_URL:-postgresql://proserv:proserv@postgres:5432/proserv_shadow}
      REDIS_URL: ${REDIS_URL:-redis://redis:6379}
      API_HOST: 0.0.0.0
      API_PORT: 4000
    depends_on:
      - postgres
      - redis
      - minio
      - mailpit
      - otel-collector
    ports:
      - '${API_PORT:-4000}:4000'

  frontend:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-http://localhost:4000/api}
      API_INTERNAL_URL: ${API_INTERNAL_URL:-http://api:4000/api}
    depends_on:
      - api
    ports:
      - '${FRONTEND_PORT:-3000}:3000'

volumes:
  proserv-postgres:
  proserv-minio:
