name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
      - run: corepack enable
      - run: pnpm install --frozen-lockfile
      - run: pnpm nx format:check
      - run: pnpm nx lint api frontend shared
      - run: pnpm nx test api frontend shared --coverage
      - run: pnpm nx build api --skip-nx-cache
      - run: pnpm nx build frontend --skip-nx-cache
